version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studentcheck"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-coz9av60fwzb"
s3_prefix = "studentcheck"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
